### ISSUE TITLE
Shall we not check graylogHost if the transport is not graylog? 

### ISSUE THREAD

**Issue by chunfengd** [tetrascience/ts-lib-logger#3]
https://github.com/tetrascience/ts-lib-logger/blob/1d89709aab757885d7640368df63bcc3ec03699c/index.js#L28

Just like the code in microsevice-boilerplate: https://github.com/tetrascience/ts-tool-microservice-boilerplate/blob/84692111985dae6b6b6bf74a027a6c27bcbfc463/config.js#L12

**Comment by spinwang** [comment]
https://github.com/tetrascience/ts-lib-logger/pull/4
